### ISSUE TITLE
Misnomer: Account

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/vocabulary#1]
An account traditionally describes the contract between a service provider and a service user. eg. "Your account with this bank has been invalidated". Accounts have a deeply monetary co-notation which does not seem appropriate for a free-in-control self generated setup.
User-accounts on an offline system are usually free to setup, but they are indicative of a multi-user setup (which we are not propagating), in a multi-user setup the account indicates the existence of other - higher - accounts (such as root/admin). Also seems misplaced.

- [Account (bookkeeping)](https://en.wikipedia.org/wiki/Account_(bookkeeping))
- [User](https://en.wikipedia.org/wiki/User_(computing))

As an interim term I suggest to use "Setup" instead. As it is quite flexible in language and helps internal communication.
eg. "Create a Setup": freshly creates a new setup "Delete your Setup" make sure that all the setup steps you did initially are torn down. It also indicates as things that need to be done before its possible to work with it. In the spirit of: "Setup the table for dinner".

Alternatively I can think of "Private Space": As in "Create your Private Space that may expose different Identities" or "Secure Zone" as in "This is a part of data that will never be shared with other people and to expose it you need to create an Avatar/Identity"

**Comment by dkastl** [comment]
So here we are with the discussion that is also in #2 . ;-)

For me "Setup" is something I don't understand in this way. For me account feels like the better word. I actually can think of it like a user account on a linux or mac computer, where I want to keep stuff separated. It's OK to create only one user account, but it's quite common to have more than one. Or on my smartphone I connect with multiple Google accounts, that are more or less separate. But I agree that the term "account" can be also seen different.

If we think what we do is different, then maybe something like "Space" is better, because it isn't used that much. "Workspace" sounds like "work". There could be a default "My Space", "Personal Space" or "Private Space".
